app_faq/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from updown.views import AddRatingFromModel

from django.conf.urls import url
from app_faq.views.question import *
from app_faq.views.comment import *
from app_faq.views.answer import *
from app_faq.views.tag import *

urlpatterns = [
    # question urls
    url(
        r'^$',
        QuestionHomePage.as_view(),
        name='question_homepage'
    ),
    url(
        r'^questions/tagged/(?P<slug>[\w-]+)/$',
        QuestionsTagged.as_view(),
        name='questions_tagged'
    ),
    url(
        r'^question/(?P<pk>[\d-]+)/$',
        QuestionRedirectView.as_view(),
        name='question_redirect'
    ),
    url(
        r'^question/(?P<pk>[\d-]+)/(?P<slug>[\w\-]+)/$',
        QuestionDetail.as_view(),
        name='question_detail'
    ),
    url(
        r'^question/create/$',
        QuestionCreate.as_view(),
        name='question_create'
    ),
    # url(
    #    r'^question/edit/(?P<pk>[\d-]+)/$',
    #    QuestionEdit.as_view(),
    #    name='question_edit'
    # ),
    url(
        r'^question/suggestion/edit/(?P<pk>[\d-]+)/$',
        QuestionSuggestedEditsCreate.as_view(),
        name='question_suggested_edits_create'
    ),
    # url(
    #    r'^question/reversions/(?P<pk>[\d-]+)/$',
    #    QuestionReversions.as_view(),
    #    name='question_reversions'
    # ),
    url(
        r'^question/reversions/(?P<pk>[\d-]+)/$',
        QuestionSuggestedEditsReversions.as_view(),
        name='question_reversions'
    ),

    # answer urls
    url(
        r'^answer/(?P<question_id>[\d-]+)/create/$',
        AnswerFormView.as_view(),
        name='answer_create'
    ),

    # comment urls
    url(
        r'^comments/create/question/(?P<pk>[\d-]+)/$',
        CommentQuestionFormView.as_view(),
        name='comment_question_create'
    ),
    url(
        r'^comments/create/answer/(?P<pk>[\d-]+)/$',
        CommentAnswerFormView.as_view(),
        name='comment_answer_create'
    ),
    url(
        r'^comments/offset/(?P<model_name>[\w\-]+)/(?P<object_id>[\d-]+)/$',
        CommentsOffsetView.as_view(),
        name='comments_offset'
    ),

    # tag urls
    url(
        r'^tags/$',
        TagListView.as_view(),
        name='tags'
    ),
    url(
        r'^tags/search/offset/$',
        TagSearchOffset.as_view(),
        name='tags_search_offset'
    ),
    url(
        r'^tags/search/json/$',
        TagSearchJSON.as_view(),
        name='tags_search_json'
    ),

    # updown url
    url(
        r'^question/(?P<object_id>\d+)/rate/(?P<score>[\d\-]+)$',
        AddRatingFromModel(), {'app_label': 'app_faq', 'model': 'Question', 'field_name': 'rating'},
        name='question_vote_rating'
    ),
    url(
        r'^answer/(?P<object_id>\d+)/rate/(?P<score>[\d\-]+)$',
        AddRatingFromModel(), {'app_label': 'app_faq', 'model': 'Answer', 'field_name': 'rating'},
        name='answer_vote_rating'
    ),
]

app_faq/models/answer.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from updown.fields import RatingField

from app_faq.models.question import Question
from app_faq.models.time import TimeStampedModel
from app_faq.models.comment import Comment


class AnswerQuerySet(models.QuerySet):

    def approved(self):
        """ whenever the answer is correct according to the author of the question """
        return self.filter(status='approved')

    def duplicated(self):
        """ mark/flag the answer as duplicated answer """
        return self.filter(status='duplicated')

    def pending(self):
        return self.filter(status='pending')

    def on_hold(self):
        return self.filter(status='on_hold')

    def closed(self):
        return self.filter(status='closed')

    def deleted(self):
        return self.filter(status='deleted')


@python_2_unicode_compatible
class Answer(TimeStampedModel):
    author = models.ForeignKey(
        User, related_name='answer_author')

    question = models.ForeignKey(
        Question, related_name='answer_question')

    STATUS_CHOICES = (
        ('approved', _('Approved')),
        ('duplicated', _('Duplicated')),
        ('pending', _('Pending')),
        ('on_hold', _('On Hold')),
        ('closed', _('Closed')),
        ('deleted', _('Deleted'))
    )
    status = models.CharField(
        _('Status'), max_length=20,
        choices=STATUS_CHOICES, default='approved')

    description = models.TextField(_('Description'))

    rating = RatingField(can_change_vote=True)

    edited = models.BooleanField(
        _('Edited?'), default=False)

    editor = models.ForeignKey(
        User, blank=True, null=True,
        on_delete=models.SET_NULL, related_name='answer_editor')

    objects = AnswerQuerySet.as_manager()

    def __str__(self):
        _title = _('%(author)s comment on %(question)s')
        return _title % {'author': self.author, 'question': self.question}

    def edits_object(self):
        answer = self
        qs = AnswerSuggestedEdits.objects.filter(answer=answer)
        if qs.exists():
            return qs.first()
        return answer

    def get_comments(self):
        """ return all comments contains with this answer """
        comments = Comment.objects.filter(object_id=self.pk,
                                          content_type__model=self._meta.model_name)
        return comments.order_by('created')  # 'rating_likes'

    def get_comments_limit(self):
        """ return maximum show the comments """
        return self.get_comments()[:settings.COMMENTS_MAX_SHOW]

    def get_comments_offset(self):
        """ return all offset comments excluded from `comments_limit` """
        comments_limit_ids = [c.id for c in self.get_comments_limit()]
        return self.get_comments().exclude(pk__in=comments_limit_ids)

    @property
    def has_offset_comments(self):
        """ to check the answer has a offset comments or not """
        return self.get_comments_offset().exists()

    class Meta:
        verbose_name_plural = _('answers')
        ordering = ['-created']


@python_2_unicode_compatible
class AnswerSuggestedEdits(TimeStampedModel):
    editor = models.ForeignKey(
        User, related_name='suggested_edits_answer_editor')

    answer = models.ForeignKey(
        Question, related_name='suggested_edits_answer')

    STATUS_CHOICES = (
        ('approved', _('Approved')),
        ('rejected', _('Rejected')),
        ('pending', _('Pending'))
    )
    status = models.CharField(
        _('Status'), max_length=20,
        choices=STATUS_CHOICES, default='pending')

    description = models.TextField(_('Description'))

    comment = models.TextField(_('Revision Comment'))

    class Meta:
        verbose_name_plural = _('answer suggested edits')
        ordering = ['-created']

app_faq/models/comment.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from updown.fields import RatingField
from app_faq.models.time import TimeStampedModel
from app_faq.models.content_type import ContentTypeToGetModel


@python_2_unicode_compatible
class Comment(TimeStampedModel, ContentTypeToGetModel):
    author = models.ForeignKey(
        User, related_name='comment_author')

    content_type = models.ForeignKey(
        ContentType, related_name='comments',
        on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField(_('Object id'))

    content_object = GenericForeignKey('content_type', 'object_id')

    comment = models.TextField(_('Comment'))

    rating = RatingField(can_change_vote=True)

    edited = models.BooleanField(
        _('Edited?'), default=False)

    def __str__(self):
        return '%s' % self.get_related_object()

    class Meta:
        verbose_name_plural = _('comments')
        ordering = ['-created']

app_faq/models/help.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from app_faq.models.time import TimeStampedModel


@python_2_unicode_compatible
class Help(TimeStampedModel):
    creator = models.ForeignKey(
        User, related_name='help_creator')

    parent = models.ForeignKey(
        'self', blank=True, null=True,
        related_name='child')

    title = models.CharField(
        _('Title'), max_length=200)

    description = models.TextField(_('Description'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = _('helps')
        ordering = ['-created']

app_faq/forms/answer.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from martor.widgets import AdminMartorWidget
from app_faq.models.answer import Answer


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['description', ]
        widgets = {'description': AdminMartorWidget()}

app_faq/forms/comment.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from app_faq.models.comment import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment', ]
        placeholder = _('Use comments to ask for more information '
                        'or suggest improvements. Avoid answering questions in comments.')
        widgets = {'comment': forms.Textarea(attrs={'placeholder': placeholder})}

app_faq/forms/question.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from martor.widgets import AdminMartorWidget
from app_faq.models.question import Question, QuestionSuggestedEdits


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['title', 'description', 'tags']
        widgets = {
            'tags': forms.SelectMultiple(attrs={'class': 'ui search fluid dropdown tags-dropdown'}),
            'title': forms.TextInput(attrs={'placeholder': _("What's your programming question? Be specific.")}),
            'description': AdminMartorWidget()
        }

# def __init__(self, *args, **kwargs):
#    super(QuestionForm, self).__init__(*args, **kwargs)
#    self.fields['tags'].widget.attrs = {'class': 'ui search fluid dropdown tags-dropdown'}


class QuestionSuggestedEditsForm(forms.ModelForm):

    class Meta:
        model = QuestionSuggestedEdits
        fields = ['title', 'description', 'tags', 'comment']
        widgets = {
            'tags': forms.SelectMultiple(attrs={'class': 'ui search fluid dropdown tags-dropdown'}),
            'title': forms.TextInput(attrs={'placeholder': _("What's your programming question? Be specific.")}),
            'description': AdminMartorWidget()
        }

app_faq/views/answer.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import (get_object_or_404, redirect)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView

from app_faq.models.question import Question
from app_faq.forms.answer import AnswerForm


class AnswerFormView(LoginRequiredMixin, FormView):
    template_name = 'app_faq/answer_create.html'
    http_method_names = [u'post', ]
    form_class = AnswerForm

    def form_valid(self, form):
        question = get_object_or_404(Question, pk=self.kwargs['question_id'])
        initial = form.save(commit=False)
        initial.author = self.request.user
        initial.question = question
        initial.save()
        messages.success(self.request, _('Your answer successfully created!'))
        return redirect(reverse('question_redirect', kwargs={'pk': question.pk}))

app_faq/views/comment.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.views.generic import (ListView, DetailView, FormView)
from django.http import JsonResponse

from app_faq.models.answer import Answer
from app_faq.models.question import Question
from app_faq.models.comment import Comment
from app_faq.forms.comment import CommentForm


class CommentFormView(LoginRequiredMixin, FormView):
    template_name = 'app_faq/comment_create.html'
    form_class = CommentForm
    model_target = None

    def get_object(self):
        return get_object_or_404(self.model_target, pk=self.kwargs['pk'])

    def form_valid(self, form):
        if self.model_target is None:
            return JsonResponse({'status': False})

        model_name = self.model_target._meta.model_name
        content_type = ContentType.objects.get(model=model_name)

        initial = form.save(commit=False)
        initial.author = self.request.user
        initial.content_type = content_type
        initial.object_id = self.get_object().pk
        initial.save()
        form.save()

        context = {
            'status': True,
            'author': self.request.user.username,
            'comment': initial.comment,
            'created': initial.created,
            'edited': initial.edited,
            'id': initial.id
        }
        # id="question-comment-{{ question.id }}"
        # id="answer-comment-{{ question.id }}"
        return JsonResponse(context)


class CommentQuestionFormView(CommentFormView):
    model_target = Question


class CommentAnswerFormView(CommentFormView):
    model_target = Answer


class CommentsOffsetView(DetailView):
    template_name = 'app_faq/comments_offset.html'

    def get_object(self):
        model_instance = None
        model_name = self.kwargs['model_name']
        object_id = self.kwargs['object_id']
        if model_name == 'question':
            model_instance = get_object_or_404(Question, pk=object_id)
        elif model_name == 'answer':
            model_instance = get_object_or_404(Answer, pk=object_id)
        return model_instance

    def get_comments_offset(self):
        if self.get_object():
            return self.get_object().get_comments_offset()
        return None

    def get_context_data(self, **kwargs):
        context = super(CommentsOffsetView, self).get_context_data(**kwargs)
        context['comments_offset'] = self.get_comments_offset()
        context['object'] = self.get_object()
        return context

app_faq/views/tag.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.views.generic import (ListView, DetailView, TemplateView)
from django.db.models.functions import Lower as LowerCase
from django.db.models import (Q, Count)

from app_faq.utils.json import JSONResponseMixin
from app_faq.utils.paginator import GenericPaginator
from app_faq.models.tag import Tag


class TagListView(ListView):
    model = Tag
    context_object_name = 'tags'
    paginate_by = settings.TAGS_PER_PAGE
    template_name = 'app_faq/tags.html'

    def get_queryset(self):
        order = self.request.GET.get('order', 'popular')
        tags = self.model.objects.order_by('-created')
        if order == 'popular':
            tags = self.model.objects.annotate(
                total=Count('question_tags')).order_by('-total')
        elif order == 'name':
            tags = self.model.objects.order_by(LowerCase('title').asc())
        elif order == 'new':
            tags = tags
        return tags

    def page_range(self):
        return GenericPaginator(
            self.get_queryset(),
            self.paginate_by,
            self.request.GET.get('page')
        ).get_page_range()

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context['page_range'] = self.page_range()
        return context


class TagSearchOffset(ListView):
    model = Tag
    context_object_name = 'tags'
    paginate_by = settings.TAGS_PER_PAGE
    template_name = 'app_faq/tags_search_offset.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return self.model.objects.filter(Q(title__startswith=query))


class TagSearchJSON(JSONResponseMixin, TemplateView):
    model = Tag

    def get_queryset(self, query):
        return list(self.model.objects.filter(
            Q(title__startswith=query)).values('title', 'slug', 'id'))

    def get(self, request, *args, **kwargs):
        context = {'success': False, 'results': []}
        query = request.GET.get('q')
        if query is not None and query.strip() != '':
            context.update({
                'success': True,
                'results': self.get_queryset(query)
            })
        return self.render_to_json_response(context)

templates/app_faq/answer_create.html
{% load i18n staticfiles %}
<form class="ui form" method="post">{% csrf_token %}
  <div class="field">
    {{ answer_form.description }}
  </div>
  <div class="field">
    <div class="ui clearing segment">
      <button class="ui right floated positive button">
        <i class="check icon"></i> {% trans "Post Your Answer" %}
      </button>
    </div>
  </div>
</form>

templates/app_faq/comment_create.html
{% load i18n %}
{% load staticfiles %}

<tr class="no-border">
  <td colspan="3">
    <form class="ui form comment-form" method="post">
      {% csrf_token %}
      <div class="ui two fields">
        <div class="ten wide field">
          {{ form.comment }}
          {% if form.comment.errors %}
            <div class="ui pointing red basic label">
              {% for error in form.comment.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="field">
          <div class="ui yellow small message message-bulletin comment-help">
            {% trans "Comment use mini-Markdown formatting:" %} <code>[link](http://example.com) _italic_ **bold** `code`</code>.
            {% blocktrans %}The comment author will always be notified of your replied comment. To also notify a previous commenter, mention their user name:{% endblocktrans %} <code>@[username]</code>.
            <a href="http://commonmark.org/help/" target="_blank">{% trans "Learn more..." %}</a>
          </div>
          <button type="submit" class="ui green labeled submit icon button">
          <i class="plus icon"></i> {% trans "Post Comment" %}
        </button>
        </div>
      </div>
    </form>
  </td>
</tr>

templates/app_faq/comments_offset.html
{% load martortags %}

{% for comment in comments_offset %}
  <tr>
    <td class="ui grey color top-align">18</td>
    <td class="top-align">
      <i class="arrow up grey link icon hover-opacity"></i><br>
      <i class="flag grey link icon hover-opacity"></i>
    </td>
    <td>
      {{ comment.comment|safe_markdown }} <a>{{ comment.author }}</a> <date class="ui grey color">{{ comment.created }}</date>
    </td>
  </tr>
{% endfor %}

templates/app_faq/question_create.html
{% extends "base.html" %}
{% load i18n staticfiles %}
{% load common_tags martortags %}
{% block title %}
  {% if question %}
    {% blocktrans with title=question.title %}Edit Question "{{ title }}"{% endblocktrans %} :: {{ block.super }}
  {% else %}
    {% trans "Ask a Question" %} :: {{ block.super }}
  {% endif %}
{% endblock %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'css/martor/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="page content">
  <div class="repo ribbon ribbon-detail">
    <div class="ui container">
      {% if question %}
        <div class="ui massive breadcrumb breadcrumb-title-detail">
          {% blocktrans with title=question.title %}Edit Question "{{ title }}"{% endblocktrans %}
        </div>
        <div class="repo options">
          <a class="ui small button spf-link" href="{% url 'question_redirect' pk=question.pk %}">
            {% trans "Back to Question" %}
          </a>
        </div>
      {% else %}
        <div class="ui massive breadcrumb breadcrumb-title-detail">{% trans "Ask a Question" %}</div>
        <div class="repo options">
          <a onclick="window.history.go(-1); return false;" class="ui small button spf-link">
            {% trans "Go Back" %}
          </a>
        </div>
      {% endif %}
    </div>
  </div>
  <div class="ui equal width vertically padded grid container">
    <div class="twelve wide column">
      <div class="answer-main" style="display:none">
        <form class="ui form" method="post">
          {% csrf_token %}
          <div class="field">
            <label>{{ form.title.label }} *</label>
            <div class="ui left icon input">
              {{ form.title }}
              <i class="terminal icon"></i>
            </div>
            {% if form.title.errors %}
              <div class="ui pointing red basic label">
                {% for error in form.title.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="ui divider padded no-border"></div>
          <div class="field">
            {{ form.description }}
          </div>
          <div class="field">
            <label>{{ form.tags.label }} *</label>
            {{ form.tags }}
            {% if form.tags.errors %}
              <div class="ui pointing red basic label">
                {% for error in form.tags.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          {% if question %}
            <div class="field">
              <label>{% trans "Edit Summary" %} *</label>
              <div class="ui left icon input">
                <input type="text" name="comment" id="id_comment" minlength="5" maxlength="200" required
                  placeholder="{% trans 'briefly explain your changes (corrected spelling, fixed grammar, improved formatting)' %}">
                <i class="comment outline icon"></i>
              </div>
            </div>
          {% endif %}
          <div class="field">
            <div class="ui clearing segment no-border post-action-segment">
              {% if question %}
                <button class="ui right floated blue button post-question-button" type="submit" disabled>
                  <i class="check icon"></i> {% trans "Update Question" %}
                </button>
                <a href="{% url 'question_redirect' pk=question.pk %}" class="ui right floated button post-question-button">
                  <i class="remove icon"></i> {% trans "Cancel" %}
                </a>
              {% else %}
                <button class="ui right floated positive button post-question-button" type="submit" disabled>
                  <i class="check icon"></i> {% trans "Post Your Question" %}
                </button>
              {% endif %}
            </div>
          </div>
        </form>
      </div><!-- end /.answer-main -->
    </div>
    <div class="column right-sidebar">
      <div class="ui fluid right vertical">
        <div class="sidebar-help sidebar-bulletin sidebar-help-title" {% if question %}style="display:none"{% endif %}>
          <h3 class="ui header">{% trans "How to Ask" %}</h3>
          <p>Is your question about programming?</p>
          <p>We prefer questions that can be answered, not just discussed.</p>
          <p>Provide details. Share your research.</p>
          <p>If your question is about this website, <a>ask it on meta</a> instead.</p>
        </div>
        <div class="sidebar-help sidebar-bulletin sidebar-help-title-edit" {% if not question %}style="display:none"{% endif %}>
          <h3 class="ui header">{% trans "How to Edit" %}</h3>
          <div class="ui list">
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">fix grammatical or spelling errors</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">clarify meaning without changing it</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">correct minor mistakes</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">add related resources or links</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content"><i>always</i> respect the original author</div>
            </div>
          </div>
        </div>
        <div class="sidebar-help sidebar-bulletin sidebar-help-description" style="display:none">
          <h3 class="ui header">{% trans "How to Format" %}</h3>
          <div class="ui list">
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">put returns between paragraphs</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">for linebreak add 2 spaces at end</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content"><i>_italic_</i> or <strong>**bold**</strong></div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">indent code by 4 spaces</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">backtick escapes <code>`like _so_`</code></div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">quote by placing > at start of line</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">to make links [foo](http://foo.com)</div>
            </div>
          </div>
        </div>
        <div class="sidebar-help sidebar-bulletin sidebar-help-tags" style="display:none">
          <h3 class="ui header">{% trans "How to Tag" %}</h3>
          <p>
            A tag is a keyword or label that categorizes your question with other, similar questions.
            Choose one or more (up to 5) tags that will help answerers to find and interpret your question.
          </p>
          <div class="ui list">
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">complete the sentence: <i>my question is about...</i></div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">use tags that describe things or concepts that are essential, not incidental to your question</div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">favor using existing <a>popular tags</a></div>
            </div>
          </div>
          <p>If your question is primarily about a topic for which you can't find a tag:</p>
          <div class="ui list">
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">
                combine multiple words into single-words with hyphens
                (e.g. <label class="ui small label">ruby-on-rails</label>), up to a maximum of 35
              </div>
            </div>
            <div class="item no-underline">
              <i class="caret right icon"></i>
              <div class="content">
                <a>creating new tags is a privilege</a>; if you can't yet create a tag you need,
                then post this question without it, then <a>ask the community to create it for you</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/martor.min.js' %}"></script>
  <script>
    setTimeout(function(){$('.answer-main').show()}, 1000);
    $('.tab-martor-menu').removeClass('secondary pointing');
    $('.martor-preview pre').each(function(i, block){hljs.highlightBlock(block)});
    //$('.ui.search.tags-dropdown').dropdown({maxSelections: 5, transition: 'fade up'});
    $('.ui.search.tags-dropdown').dropdown({
      placeholder: '{% trans "at least one tag such as (sql css mysql), max 5 tags" %}',
      allowAdditions: false,
      apiSettings: {
        url: '{% url "tags_search_json" %}?q={query}'
      },
      fields: {
        remoteValues : 'results',
        name         : 'title',
        text         : 'title',
        value        : 'id'
      },
    }).dropdown('restore defaults');

    var disabledPostButton = function() {
      if($('textarea[name=description]').val().length >= 10) {
        $('.post-question-button').removeAttr('disabled');
      }else {
        $('.post-question-button').attr({'disabled': 'disabled'});
      }
    }
    disabledPostButton();
    $(document).keyup(function(){disabledPostButton()});

    var showHelp = function(selector) {
      $('.sidebar-help').hide();
      $(selector).show();
    }
    $(document).on('click', '.martor-field-description', function(){
      showHelp('.sidebar-help-description');
    });
    $('#id_title').click(function(){
      {% if question %}{# edit mode #}
        showHelp('.sidebar-help-title-edit');
      {% else %}{# create mode #}
        showHelp('.sidebar-help-title');
      {% endif %}
    });
    $('.tags-dropdown').click(function(){
      showHelp('.sidebar-help-tags');
    });
  </script>
{% endblock %}

templates/app_faq/question_edit.html
{% extends "app_faq/question_create.html" %}
{% load i18n %}